apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-python
  labels:
    app: day1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: day1
  template:
    metadata:
      labels:
        app: day1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: disktype
                    operator: In
                    values:
                      - ssd
      containers:
        - name: python-app-container
          image: nikhilmourya/myapp.v1
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
